@startuml
actor AgentPersonalny
actor AgentCentralnyPlanujący
actor AgentPokojuSpotkań
actor AgenciPersonalniUczestnikow
actor AgenciPokojówSpotkań

AgentPersonalny -> AgentCentralnyPlanujący : meet_request
alt if needed
	loop OcenaMożliwościPrzeprowadzeniaSpotkania​
		AgentCentralnyPlanujący -> AgenciPersonalniUczestnikow : messages
		AgenciPersonalniUczestnikow -> AgentCentralnyPlanujący : messages
		AgentCentralnyPlanujący -> AgenciPokojówSpotkań : messages
		AgenciPokojówSpotkań -> AgentCentralnyPlanujący : messages
	end
end
AgentCentralnyPlanujący -> AgentPokojuSpotkań : new_meeting_inform
AgentCentralnyPlanujący -> AgenciPersonalniUczestnikow : new_meeting_inform
AgentCentralnyPlanujący -> AgentPersonalny : meet_inform
@enduml